const GIB = 1024 ** 3;

function gib(value) {
  return Math.round(value * GIB);
}

function demoArtifact({
  id,
  agent,
  agentName,
  type,
  label,
  displayPath,
  sizeGiB,
  files,
  modifiedAt,
  ageDays,
  status,
  confidence = 'high',
  reasons,
  evidence,
  references = [],
  git = null,
  cleanup = { eligible: false, strategy: null },
  owner,
}) {
  return {
    id,
    agent,
    agentName,
    type,
    label,
    path: displayPath.replace(/^~/, '/Users/alex'),
    displayPath,
    sizeBytes: gib(sizeGiB),
    fileCount: files,
    modifiedAt,
    ageDays,
    status,
    confidence,
    reasons,
    evidence,
    references,
    git,
    cleanup,
    metadata: {
      owner,
      sample: true,
    },
  };
}

/**
 * Build the deterministic report used by `agentmop demo` and screenshots.
 * Every value is fictional and deliberately labelled as sample data.
 */
export function createDemoReport() {
  const artifacts = [
    demoArtifact({
      id: 'claude-wt-71g',
      agent: 'claude',
      agentName: 'Claude Code',
      type: 'worktree',
      label: 'Linked worktree: feature/checkout-api-v2',
      displayPath: '~/.claude/worktrees/checkout-api-v2',
      sizeGiB: 71.6,
      files: 184_220,
      modifiedAt: '2026-08-10T09:26:00.000Z',
      ageDays: 0,
      status: 'dirty',
      reasons: ['Git reports modified or untracked files'],
      evidence: ['HEAD 51bd4ae', 'Branch feature/checkout-api-v2'],
      references: ['Claude Code session 67be…91d2 references ~/.claude/worktrees/checkout-api-v2'],
      git: {
        branch: 'feature/checkout-api-v2',
        dirty: true,
        head: '51bd4ae',
        linked: true,
        registered: true,
        mainWorktree: '/Users/alex/Projects/checkout-api',
      },
      owner: 'Claude Code managed linked worktree',
    }),
    demoArtifact({
      id: 'codex-wt-42g',
      agent: 'codex',
      agentName: 'Codex',
      type: 'worktree',
      label: 'Linked worktree: feat/sync-engine',
      displayPath: '~/.codex/worktrees/desktop-sync',
      sizeGiB: 42.8,
      files: 96_104,
      modifiedAt: '2026-08-10T09:29:00.000Z',
      ageDays: 0,
      status: 'live',
      reasons: ['An active agent process references this worktree'],
      evidence: ['PID 48217 (Codex)'],
      references: ['PID 48217 references this path', 'Codex session 019f…790d references ~/.codex/worktrees/desktop-sync'],
      git: {
        branch: 'feat/sync-engine',
        dirty: false,
        head: 'ab8913f',
        linked: true,
        registered: true,
        mainWorktree: '/Users/alex/Projects/desktop-sync',
      },
      owner: 'Codex managed linked worktree',
    }),
    demoArtifact({
      id: 'cursor-cache-31g',
      agent: 'cursor',
      agentName: 'Cursor',
      type: 'cache',
      label: 'Cache',
      displayPath: '~/.cursor/cache',
      sizeGiB: 31.4,
      files: 52_801,
      modifiedAt: '2026-05-02T17:11:00.000Z',
      ageDays: 99,
      status: 'safe',
      reasons: ['Known agent cache or temporary path is stale and unreferenced'],
      evidence: ['Fresh process scan found no references', 'Last content change was 99 day(s) ago'],
      cleanup: { eligible: true, strategy: 'move' },
      owner: 'Cursor known cache path',
    }),
    demoArtifact({
      id: 'claude-sessions-22g',
      agent: 'claude',
      agentName: 'Claude Code',
      type: 'history',
      label: 'Project sessions',
      displayPath: '~/.claude/projects',
      sizeGiB: 22.7,
      files: 8_642,
      modifiedAt: '2026-06-14T03:42:00.000Z',
      ageDays: 57,
      status: 'review',
      reasons: ['Session and history data may be resumable or personally valuable', 'AgentMop never automatically cleans session history'],
      evidence: ['Last content change was 57 day(s) ago'],
      references: ['Claude Code session 67be…91d2 references ~/Projects/payments'],
      owner: 'Claude Code known history path',
    }),
    demoArtifact({
      id: 'codex-cache-18g',
      agent: 'codex',
      agentName: 'Codex',
      type: 'cache',
      label: 'Cache',
      displayPath: '~/.codex/cache',
      sizeGiB: 18.2,
      files: 31_012,
      modifiedAt: '2026-04-01T10:05:00.000Z',
      ageDays: 131,
      status: 'safe',
      reasons: ['Known agent cache or temporary path is stale and unreferenced'],
      evidence: ['Fresh process scan found no references', 'Last content change was 131 day(s) ago'],
      cleanup: { eligible: true, strategy: 'move' },
      owner: 'Codex known cache path',
    }),
    demoArtifact({
      id: 'opencode-temp-8g',
      agent: 'opencode',
      agentName: 'OpenCode',
      type: 'temp',
      label: 'Temporary agent data',
      displayPath: '~/.local/share/opencode/tmp',
      sizeGiB: 8.9,
      files: 28_303,
      modifiedAt: '2026-07-01T23:18:00.000Z',
      ageDays: 39,
      status: 'unknown',
      confidence: 'low',
      reasons: ['Filesystem inspection was incomplete'],
      evidence: ['1 path(s) could not be inspected'],
      owner: 'OpenCode known temp path',
    }),
    demoArtifact({
      id: 'cursor-temp-4g',
      agent: 'cursor',
      agentName: 'Cursor',
      type: 'temp',
      label: 'Temporary agent data',
      displayPath: '/private/tmp/cursor-stale-task',
      sizeGiB: 4.8,
      files: 6_430,
      modifiedAt: '2026-01-09T07:20:00.000Z',
      ageDays: 213,
      status: 'safe',
      reasons: ['Known agent cache or temporary path is stale and unreferenced'],
      evidence: ['Fresh process scan found no references', 'Last content change was 213 day(s) ago'],
      references: ['Cursor session cursor-019f references /private/tmp/cursor-stale-task'],
      cleanup: { eligible: true, strategy: 'move' },
      owner: 'Cursor temporary path',
    }),
    demoArtifact({
      id: 'opencode-history-2g',
      agent: 'opencode',
      agentName: 'OpenCode',
      type: 'history',
      label: 'Session storage',
      displayPath: '~/.local/share/opencode/storage',
      sizeGiB: 2,
      files: 2_964,
      modifiedAt: '2025-12-31T16:00:00.000Z',
      ageDays: 222,
      status: 'review',
      reasons: ['Session and history data may be resumable or personally valuable', 'AgentMop never automatically cleans session history'],
      evidence: ['Last content change was 222 day(s) ago'],
      owner: 'OpenCode known history path',
    }),
  ];

  const agentNames = new Map([
    ['claude', 'Claude Code'],
    ['codex', 'Codex'],
    ['cursor', 'Cursor'],
    ['opencode', 'OpenCode'],
  ]);
  const agents = [...agentNames].map(([id, name]) => {
    const owned = artifacts.filter((artifact) => artifact.agent === id);
    return {
      id,
      name,
      installed: true,
      totalBytes: owned.reduce((total, artifact) => total + artifact.sizeBytes, 0),
      artifactCount: owned.length,
    };
  });

  const processes = [
    {
      pid: 48217,
      ppid: 934,
      agent: 'codex',
      agentName: 'Codex',
      executable: 'codex',
      command: 'codex …',
      elapsedSeconds: 6_138,
      rssBytes: 842_006_528,
      cwd: '/Users/alex/.codex/worktrees/desktop-sync',
      references: ['/Users/alex/.codex/worktrees/desktop-sync'],
      status: 'live',
      reasons: ['Observed running process; AgentMop never stops processes'],
      detachedCandidate: false,
      observedOnly: true,
    },
    {
      pid: 49802,
      ppid: 49788,
      agent: 'claude',
      agentName: 'Claude Code',
      executable: 'claude',
      command: 'claude …',
      elapsedSeconds: 1_124,
      rssBytes: 391_118_848,
      cwd: '/Users/alex/Projects/checkout',
      references: ['/Users/alex/Projects/checkout'],
      status: 'live',
      reasons: ['Observed running process; AgentMop never stops processes'],
      detachedCandidate: false,
      observedOnly: true,
    },
    {
      pid: 50190,
      ppid: 1,
      agent: 'cursor',
      agentName: 'Cursor',
      executable: 'Cursor Helper (Plugin)',
      command: 'Cursor Helper (Plugin) …',
      elapsedSeconds: 309,
      rssBytes: 216_006_656,
      cwd: '/Users/alex/Projects/editor',
      references: ['/Users/alex/Projects/editor'],
      status: 'live',
      reasons: ['Observed running process; AgentMop never stops processes', 'PPID 1; verify before stopping'],
      detachedCandidate: true,
      observedOnly: true,
    },
  ];

  const counts = { live: 0, dirty: 0, safe: 0, review: 0, unknown: 0 };
  for (const artifact of artifacts) counts[artifact.status] += 1;
  const totalBytes = artifacts.reduce((total, artifact) => total + artifact.sizeBytes, 0);
  const safeBytes = artifacts
    .filter((artifact) => artifact.status === 'safe' && artifact.cleanup?.eligible)
    .reduce((total, artifact) => total + artifact.sizeBytes, 0);
  const reviewBytes = artifacts
    .filter((artifact) => artifact.status === 'review' || artifact.status === 'unknown')
    .reduce((total, artifact) => total + artifact.sizeBytes, 0);

  return {
    version: '1',
    generatedAt: '2026-08-10T09:30:00.000Z',
    platform: 'darwin-arm64',
    hostname: 'sample-macbook',
    home: '/Users/alex',
    sampleData: true,
    sampleLabel: 'Sample data — no files were scanned',
    agents,
    artifacts,
    processes,
    warnings: ['Demo mode: every path, process, size, and status on this page is fictional sample data.'],
    summary: {
      totalBytes,
      safeBytes,
      reviewBytes,
      artifactCount: artifacts.length,
      processCount: processes.length,
      counts,
    },
  };
}
